# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/app/backend # steps will run in directory app/backend

    docker: # run the steps with Docker
      - image: circleci/node:9.9 # image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - run:
          name: backend-npm-update
          command: 'sudo npm install -g npm@latest'

      - restore_cache: # special step to restore the dependency cache
          name: backend-restore-cache
          key: dependency-cache-{{ checksum "backend/package.json" }}

      - run:
          name: backend-npm-install
          command: npm install

      - save_cache: # special step to save the dependency cache
          name: backend-save-cache
          key: dependency-cache-{{ checksum "backend/package.json" }}
          paths:
            - ./backend/node_modules

    working_directory: ~/app/frontend # steps will run in directory app/backend

    steps:
      - checkout

      - run:
          name: frontend-npm-update
          command: 'sudo npm install -g npm@latest'
